# CafecaBackend Default Config

title = "BoltCA"

[base]
folder = "BoltCA"
debug = false

[blockchain]
type = "ethereum"

[bolt]
agent = "54.173.59.238"
apiKey = "kissmyass"
venderID = "coinprovider"

[database]
type = "firebase"

[api]
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo",
  "post | /certificate | Bot.APICrawler.certificateFrom",
  "post | /search | Bot.APICrawler.search",
  "post | /certificate/file | Bot.APICrawler.certificateFile",
  "post | /search/file | Bot.APICrawler.searchFile",
  "post | /base64 | Bot.APICrawler.toBase64"
]